package services

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"strings"
)

// GenericRoutes is the fallback route pool used for custom services added via
// --add or --services-file when the user supplies no routes of their own.
// Every entry is a plausible first-hit for a browser or API client; responses
// (including 404s) are generated by the target app itself and therefore reset
// Render's idle timer.
var GenericRoutes = []Route{
	{Path: "/", Weight: 10},
	{Path: "/api", Weight: 6},
	{Path: "/api/health", Weight: 6},
	{Path: "/health", Weight: 5},
	{Path: "/api/status", Weight: 5},
	{Path: "/status", Weight: 3},
	{Path: "/favicon.ico", Weight: 5},
}

// AddOptions carries the custom-service inputs from the command line.
type AddOptions struct {
	Adds      []string // each "name=url" (or a bare https://host)
	Removes   []string // service names to drop, applied last
	File      string   // --services-file
	NoBuiltin bool     // --no-builtin
}

// CustomService is the JSON shape accepted by --services-file. Routes and
// weights are optional; a route without a weight gets weight 1.
type CustomService struct {
	Name    string        `json:"name"`
	BaseURL string        `json:"url"`
	Routes  []CustomRoute `json:"routes"`
}

type CustomRoute struct {
	Path   string          `json:"path"`
	Weight json.RawMessage `json:"weight,omitempty"`
}

// Compose merges built-in services, file-defined services, and --add entries
// into the final fleet. Precedence: an entry with the same name replaces an
// earlier one (file entries override built-ins, --add overrides both).
func Compose(opts AddOptions) ([]Service, error) {
	fleet := make([]Service, 0, len(All)+len(opts.Adds))
	if !opts.NoBuiltin {
		fleet = append(fleet, All...)
	}
	if opts.File != "" {
		fileSvcs, err := loadFile(opts.File)
		if err != nil {
			return nil, err
		}
		fleet = mergeByName(fleet, fileSvcs)
	}
	addSvcs, err := parseAdds(opts.Adds)
	if err != nil {
		return nil, err
	}
	fleet = mergeByName(fleet, addSvcs)
	fleet, err = removeByName(fleet, opts.Removes)
	if err != nil {
		return nil, err
	}
	if len(fleet) == 0 {
		return nil, fmt.Errorf("no services left after --add/--remove/--no-builtin")
	}
	return fleet, nil
}

// removeByName drops the named services; unknown names are an error so typos
// never silently leave a service being pinged (or not) by accident.
func removeByName(fleet []Service, names []string) ([]Service, error) {
	if len(names) == 0 {
		return fleet, nil
	}
	known := make(map[string]bool, len(fleet))
	for _, s := range fleet {
		known[s.Name] = true
	}
	drop := make(map[string]bool, len(names))
	for _, n := range names {
		if !known[n] {
			return nil, fmt.Errorf("--remove: no service named %q (use --list-services to view active services)", n)
		}
		drop[n] = true
	}
	out := fleet[:0]
	for _, s := range fleet {
		if !drop[s.Name] {
			out = append(out, s)
		}
	}
	return out, nil
}

func loadFile(path string) ([]Service, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("--services-file: %w", err)
	}
	var defs []CustomService
	if err := json.Unmarshal(raw, &defs); err != nil {
		return nil, fmt.Errorf("--services-file %s: invalid JSON: %w", path, err)
	}
	svcs := make([]Service, 0, len(defs))
	for i, d := range defs {
		s, err := d.toService(fmt.Sprintf("%s[%d]", path, i))
		if err != nil {
			return nil, err
		}
		svcs = append(svcs, s)
	}
	return svcs, nil
}

func parseAdds(adds []string) ([]Service, error) {
	svcs := make([]Service, 0, len(adds))
	for _, a := range adds {
		name, baseURL := a, ""
		if n, u, ok := strings.Cut(a, "="); ok && n != "" && u != "" {
			name, baseURL = n, u
		} else {
			// bare URL: derive the service name from its host
			parsed, err := url.Parse(strings.TrimSpace(a))
			if err != nil || parsed.Host == "" || !strings.Contains(parsed.Host, ".") {
				return nil, fmt.Errorf("--add expects name=url, got %q", a)
			}
			baseURL = a
			name = strings.SplitN(parsed.Host, ".", 2)[0]
		}
		s, err := CustomService{Name: name, BaseURL: baseURL}.toService("--add " + a)
		if err != nil {
			return nil, err
		}
		svcs = append(svcs, s)
	}
	return svcs, nil
}

func (c CustomService) toService(origin string) (Service, error) {
	if c.Name == "" {
		return Service{}, fmt.Errorf("%s: service name is required", origin)
	}
	if c.BaseURL == "" {
		return Service{}, fmt.Errorf("%s: service %q needs a url", origin, c.Name)
	}
	base, err := normalizeBaseURL(c.BaseURL)
	if err != nil {
		return Service{}, fmt.Errorf("%s: service %q: %w", origin, c.Name, err)
	}
	routes := make([]Route, 0, len(c.Routes)+len(GenericRoutes))
	for i, r := range c.Routes {
		if r.Path == "" {
			return Service{}, fmt.Errorf("%s: service %q route[%d] needs a path", origin, c.Name, i)
		}
		if !strings.HasPrefix(r.Path, "/") {
			return Service{}, fmt.Errorf("%s: service %q route %q must start with /", origin, c.Name, r.Path)
		}
		w, err := rawWeight(r.Weight, 1)
		if err != nil {
			return Service{}, fmt.Errorf("%s: service %q route %q: %w", origin, c.Name, r.Path, err)
		}
		routes = append(routes, Route{Path: r.Path, Weight: w})
	}
	if len(routes) == 0 {
		routes = append(routes, GenericRoutes...)
	}
	return Service{Name: c.Name, BaseURL: base, Routes: routes}, nil
}

// rawWeight decodes a JSON number given either as 5 or "5". Default is d.
func rawWeight(raw json.RawMessage, d int) (int, error) {
	if len(raw) == 0 {
		return d, nil
	}
	var n int
	if err := json.Unmarshal(raw, &n); err != nil {
		return 0, fmt.Errorf("weight must be an integer, got %s", raw)
	}
	if n < 1 {
		return 0, fmt.Errorf("weight must be >= 1, got %d", n)
	}
	return n, nil
}

func normalizeBaseURL(rawURL string) (string, error) {
	u, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil {
		return "", fmt.Errorf("invalid url %q: %w", rawURL, err)
	}
	if u.Scheme == "" {
		u, err = url.Parse("https://" + strings.TrimSpace(rawURL))
		if err != nil {
			return "", fmt.Errorf("invalid url %q", rawURL)
		}
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return "", fmt.Errorf("url %q must use http or https", rawURL)
	}
	if u.Host == "" {
		return "", fmt.Errorf("url %q has no host", rawURL)
	}
	u.Path = strings.TrimSuffix(u.Path, "/")
	u.RawQuery = ""
	u.Fragment = ""
	return u.String(), nil
}

func mergeByName(base, extra []Service) []Service {
	out := base
	for _, s := range extra {
		replaced := false
		for i := range out {
			if out[i].Name == s.Name {
				out[i] = s
				replaced = true
				break
			}
		}
		if !replaced {
			out = append(out, s)
		}
	}
	return out
}
